//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRI_RMS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TG.RMSCLIENT.WEB.Resource.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT US.
        /// </summary>
        public static string ABOUT_US {
            get {
                return ResourceManager.GetString("ABOUT_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BBQ.
        /// </summary>
        public static string BBQ {
            get {
                return ResourceManager.GetString("BBQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOG.
        /// </summary>
        public static string BLOG {
            get {
                return ResourceManager.GetString("BLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breakfast Items.
        /// </summary>
        public static string Breakfast_Items {
            get {
                return ResourceManager.GetString("Breakfast_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BROWSE MORE.
        /// </summary>
        public static string BROWSE_MORE {
            get {
                return ResourceManager.GetString("BROWSE_MORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee Items.
        /// </summary>
        public static string Coffee_Items {
            get {
                return ResourceManager.GetString("Coffee_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTACT.
        /// </summary>
        public static string CONTACT {
            get {
                return ResourceManager.GetString("CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delicious.
        /// </summary>
        public static string Delicious {
            get {
                return ResourceManager.GetString("Delicious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        public static string Discover {
            get {
                return ResourceManager.GetString("Discover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Email_Address {
            get {
                return ResourceManager.GetString("Email_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving..
        /// </summary>
        public static string Error_saving {
            get {
                return ResourceManager.GetString("Error_saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fresh.
        /// </summary>
        public static string Fresh {
            get {
                return ResourceManager.GetString("Fresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FROM OUR BLOG.
        /// </summary>
        public static string FROM_OUR_BLOG {
            get {
                return ResourceManager.GetString("FROM_OUR_BLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GALLERY.
        /// </summary>
        public static string GALLERY {
            get {
                return ResourceManager.GetString("GALLERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get In Touch.
        /// </summary>
        public static string Get_In_Touch {
            get {
                return ResourceManager.GetString("Get_In_Touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GREEN FOODS.
        /// </summary>
        public static string GREEN_FOODS {
            get {
                return ResourceManager.GetString("GREEN_FOODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string HOME {
            get {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot.
        /// </summary>
        public static string Hot {
            get {
                return ResourceManager.GetString("Hot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANGUAGE.
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest News.
        /// </summary>
        public static string Latest_News {
            get {
                return ResourceManager.GetString("Latest_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunch Items.
        /// </summary>
        public static string Lunch_Items {
            get {
                return ResourceManager.GetString("Lunch_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make A.
        /// </summary>
        public static string Make_A {
            get {
                return ResourceManager.GetString("Make_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Reservation.
        /// </summary>
        public static string Make_Reservation {
            get {
                return ResourceManager.GetString("Make_Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENU.
        /// </summary>
        public static string MENU {
            get {
                return ResourceManager.GetString("MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR BAR.
        /// </summary>
        public static string OUR_BAR {
            get {
                return ResourceManager.GetString("OUR_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Gallery.
        /// </summary>
        public static string Our_Gallery {
            get {
                return ResourceManager.GetString("Our_Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR MENU.
        /// </summary>
        public static string OUR_MENU {
            get {
                return ResourceManager.GetString("OUR_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Reception.
        /// </summary>
        public static string Our_Reception {
            get {
                return ResourceManager.GetString("Our_Reception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait...
        /// </summary>
        public static string Please_wait {
            get {
                return ResourceManager.GetString("Please_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READ MORE.
        /// </summary>
        public static string READ_MORE {
            get {
                return ResourceManager.GetString("READ_MORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        public static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESEVATION.
        /// </summary>
        public static string RESEVATION {
            get {
                return ResourceManager.GetString("RESEVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satisfied.
        /// </summary>
        public static string Satisfied {
            get {
                return ResourceManager.GetString("Satisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully..
        /// </summary>
        public static string Saved_successfully {
            get {
                return ResourceManager.GetString("Saved_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string Send_Message {
            get {
                return ResourceManager.GetString("Send_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPICY MASALAS.
        /// </summary>
        public static string SPICY_MASALAS {
            get {
                return ResourceManager.GetString("SPICY_MASALAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBSCRIBE.
        /// </summary>
        public static string SUBSCRIBE {
            get {
                return ResourceManager.GetString("SUBSCRIBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testimonials.
        /// </summary>
        public static string Testimonials {
            get {
                return ResourceManager.GetString("Testimonials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO THE KING FOOD.
        /// </summary>
        public static string TO_THE_KING_FOOD {
            get {
                return ResourceManager.GetString("TO_THE_KING_FOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        public static string Welcome_to {
            get {
                return ResourceManager.GetString("Welcome_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What Customers Say.
        /// </summary>
        public static string What_Customers_Say {
            get {
                return ResourceManager.GetString("What_Customers_Say", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string Your_Name {
            get {
                return ResourceManager.GetString("Your_Name", resourceCulture);
            }
        }
    }
}
